#!/bin/bash

/usr/local/snap/bin/snap --nosplash --nogui --modules --refresh --update org.csa.rstb.rstb.op.polarimetric.tools \
  org.esa.s2tbx.s2tbx.s2msi.reader \
  org.esa.snap.snap.temporal.percentile \
  org.esa.snap.snap.unmix.ui \
  org.esa.snap.snap.pgx.reader \
  org.esa.snap.snap.remote.products.repository \
  org.esa.s2tbx.s2tbx.forest.cover.change \
  org.esa.snap.snap.smart.configurator.ui \
  org.esa.s3tbx.s3tbx.landsat.reader \
  org.esa.s2tbx.s2tbx.alosAV2.reader \
  org.esa.s3tbx.s3tbx.sentinel3.reader \
  org.esa.snap.snap.python \
  org.esa.s2tbx.s2tbx.worldview2esa.reader \
  org.esa.s1tbx.s1tbx.kit \
  org.esa.s2tbx.s2tbx.gdal.reader \
  org.esa.snap.snap.remote.execution.ui \
  org.esa.snap.globcover.worldmap \
  org.esa.snap.snap.branding \
  org.esa.snap.snap.core \
  org.esa.s3tbx.s3tbx.spot.vgt.reader \
  org.esa.s3tbx.s3tbx.sentinel3.reader.ui \
  org.esa.snap.snap.smart.configurator \
  org.esa.s2tbx.s2tbx.land.cover \
  org.esa.snap.snap.statistics \
  org.esa.s1tbx.s1tbx.commons \
  org.esa.s3tbx.s3tbx.mphchl \
  org.esa.s3tbx.s3tbx.meris.l2auxdata \
  org.csa.rstb.rstb.op.calibration \
  org.esa.snap.ceres.ui \
  org.esa.s3tbx.s3tbx.o2a.harmonisation \
  org.csa.rstb.rstb.op.soil.moisture \
  org.esa.s3tbx.s3tbx.aatsr.sst.ui \
  org.esa.snap.snap.collocation \
  org.esa.s3tbx.s3tbx.olci.radiometry \
  org.esa.s2tbx.s2tbx.radiometric.indices.ui \
  org.esa.snap.snap.gpf.ui \
  org.esa.snap.ceres.core \
  org.esa.snap.snap.raster \
  org.esa.s3tbx.s3tbx.slstr.regrid \
  org.esa.snap.snap.csv.dataio \
  org.esa.snap.snap.pixel.extraction \
  org.esa.snap.seadas.seadas.reader.ui \
  org.esa.s1tbx.s1tbx.op.analysis.ui \
  org.esa.snap.snap.binning \
  org.esa.s1tbx.s1tbx.op.feature.extraction \
  org.esa.s3tbx.s3tbx.merisl3.reader \
  org.esa.snap.snap.pixel.extraction.ui \
  org.esa.s3tbx.s3tbx.fub.wew.ui \
  org.esa.s2tbx.s2tbx.spot.reader \
  org.esa.s2tbx.s2tbx.radiometric.indices \
  org.esa.snap.snap.gpf \
  org.esa.snap.snap.land.cover.ui \
  org.esa.s2tbx.s2tbx.muscate.reader \
  org.esa.snap.snap.bigtiff \
  org.esa.snap.snap.tango \
  org.esa.s2tbx.s2tbx.grm.ui \
  org.esa.s3tbx.s3tbx.meris.smac \
  org.esa.smostbx.smos.tools \
  org.esa.s1tbx.s1tbx.op.sar.processing \
  org.esa.snap.snap.arcbingrid.reader \
  org.esa.snap.snap.envisat.reader \
  org.esa.s3tbx.s3tbx.insitu.client.ui \
  org.esa.s2tbx.s2tbx.rapideye.reader \
  org.esa.smostbx.smos.gui \
  org.esa.snap.snap.worldwind \
  org.esa.s1tbx.s1tbx.rcp \
  org.esa.snap.ceres.glayer \
  org.esa.s3tbx.s3tbx.arc.ui \
  org.esa.s2tbx.s2tbx.gdal.writer \
  org.csa.rstb.rstb.op.soil.moisture.ui \
  org.csa.rstb.rstb.op.classification.ui \
  org.esa.snap.snap.pconvert \
  org.esa.snap.snap.geotiff \
  org.esa.snap.snap.virtual.file.system.ui \
  org.esa.snap.snap.rcp \
  org.esa.s3tbx.s3tbx.atsr.reader \
  org.esa.s1tbx.s1tbx.op.insar \
  org.esa.snap.snap.classification \
  org.esa.snap.snap.cluster.analysis \
  org.esa.s2tbx.s2tbx.gdal.writer.ui \
  org.esa.snap.snap.classification.ui \
  org.esa.s1tbx.s1tbx.op.calibration.ui \
  org.esa.snap.snap.getasse30.dem \
  org.esa.s2tbx.s2tbx.ikonos.reader \
  org.esa.s3tbx.s3tbx.c2rcc \
  org.esa.snap.snap.watermask.ui \
  org.esa.snap.snap.virtual.file.system \
  org.esa.s2tbx.s2tbx.worldview2.reader \
  org.csa.rstb.rstb.kit \
  org.esa.s2tbx.s2tbx.biophysical \
  org.esa.smostbx.smos.reader \
  org.esa.s3tbx.s3tbx.meris.brr \
  org.esa.s1tbx.s1tbx.op.utilities.ui \
  org.esa.snap.snap.sta \
  org.esa.s1tbx.s1tbx.cloud \
  org.esa.snap.seadas.seadas.reader \
  org.esa.snap.snap.watermask \
  org.esa.s1tbx.s1tbx.op.ocean.ui \
  org.esa.smostbx.smos.kit \
  org.esa.snap.snap.collocation.ui \
  org.esa.snap.snap.dem \
  org.esa.snap.snap.envi.reader \
  org.esa.snap.lib.openjpeg \
  org.esa.snap.snap.netcdf \
  org.esa.s3tbx.s3tbx.arc \
  org.esa.s3tbx.s3tbx.alos.reader \
  org.esa.s1tbx.s1tbx.io.ephemeris \
  org.esa.s2tbx.s2tbx.spectral.angle.mapper \
  org.esa.snap.snap.virtual.file.system.preferences.ui \
  org.esa.s1tbx.s1tbx.op.utilities \
  org.esa.s2tbx.s2tbx.s2msi.reader.ui \
  org.esa.s2tbx.s2tbx.coregistration.ui \
  org.esa.s3tbx.s3tbx.fub.wew \
  org.esa.snap.snap.binning.ui \
  org.esa.s3tbx.s3tbx.owt.classification \
  org.esa.s2tbx.lib.gdal \
  org.esa.s2tbx.s2tbx.kompsat2.reader \
  org.esa.s1tbx.s1tbx.op.feature.extraction.ui \
  org.esa.s3tbx.s3tbx.avhrr.reader \
  org.esa.snap.ceres.jai \
  org.esa.s2tbx.s2tbx.s2msi.mci.ui \
  org.esa.s2tbx.s2tbx.coregistration \
  org.esa.s2tbx.s2tbx.reflectance.to.radiance \
  org.esa.snap.blue.marble.worldmap \
  org.esa.snap.snap.hdf5.writer \
  org.esa.snap.snap.land.cover \
  org.esa.s3tbx.s3tbx.modis.reader \
  org.esa.s3tbx.s3tbx.rad2refl \
  com.iceye.esa.snap.iceye.slc.reader \
  org.csa.rstb.rstb.op.classification \
  org.csa.rstb.rstb.op.polarimetric.tools.ui \
  org.esa.s2tbx.s2tbx.alosPRI.reader \
  org.esa.s2tbx.s2tbx.pleiades.reader \
  org.esa.s3tbx.s3tbx.slstr.pdu.stitching.ui \
  org.esa.s2tbx.s2tbx.preferences.ui \
  org.esa.s3tbx.s3tbx.flhmci \
  org.esa.s2tbx.s2tbx.forest.cover.change.ui \
  org.esa.snap.snap.product.library.v2 \
  org.esa.s2tbx.s2tbx.commons \
  org.esa.s2tbx.s2tbx.cache \
  org.esa.s3tbx.s3tbx.aatsr.sst \
  org.esa.snap.snap.help \
  org.esa.smostbx.smos.ee2netcdf.ui \
  org.esa.s3tbx.s3tbx.meris.ops \
  org.esa.snap.snap.ui \
  org.esa.s2tbx.s2tbx.s2msi.resampler \
  org.esa.s2tbx.s2tbx.spectral.angle.mapper.ui \
  org.esa.snap.snap.product.library.ui.v2 \
  org.esa.s3tbx.s3tbx.flhmci.ui \
  org.esa.s3tbx.s3tbx.meris.radiometry \
  org.esa.smostbx.smos.dgg \
  org.esa.s3tbx.s3tbx.kit \
  org.esa.s3tbx.s3tbx.meris.radiometry.ui \
  org.esa.smostbx.smos.lsmask \
  org.esa.snap.ceres.binio \
  org.esa.s1tbx.s1tbx.op.sar.processing.ui \
  org.esa.snap.ceres.binding \
  org.esa.snap.snap.raster.ui \
  org.esa.snap.snap.engine.kit \
  org.esa.snap.snap.sta.ui \
  org.esa.s2tbx.s2tbx.reflectance.to.radiance.ui \
  org.csa.rstb.rstb.io \
  org.esa.snap.snap.jp2.reader \
  org.esa.snap.snap.engine.utilities \
  org.esa.s3tbx.s3tbx.ppe.operator \
  org.esa.snap.snap.dem.ui \
  org.esa.s2tbx.s2tbx.deimos.reader \
  org.esa.s1tbx.s1tbx.op.sentinel1.ui \
  org.esa.snap.ceres.metadata \
  org.esa.s2tbx.s2tbx.spot6.reader \
  org.esa.s1tbx.s1tbx.op.sentinel1 \
  org.esa.s1tbx.s1tbx.op.insar.ui \
  org.esa.smostbx.smos.ee2netcdf \
  org.esa.s2tbx.s2tbx.cache.ui \
  org.esa.s3tbx.s3tbx.slstr.pdu.stitching \
  org.esa.s2tbx.s2tbx.sta.adapters.help \
  org.esa.s3tbx.s3tbx.meris.sdr \
  org.esa.snap.snap.graph.builder \
  org.esa.s2tbx.s2tbx.kit \
  org.esa.s1tbx.s1tbx.io \
  org.esa.s3tbx.s3tbx.rad2refl.ui \
  org.esa.s2tbx.lib.gdal.preferences.ui \
  org.esa.s2tbx.s2tbx.s2msi.mci \
  org.esa.snap.snap.unmix \
  org.esa.s2tbx.s2tbx.grm \
  org.esa.snap.snap.remote.execution \
  org.esa.snap.snap.ndvi \
  org.esa.s2tbx.s2tbx.jp2.writer \
  org.esa.s3tbx.s3tbx.meris.cloud \
  org.esa.s3tbx.s3tbx.fu.operator \
  org.esa.s1tbx.s1tbx.op.calibration

#  2>&1 | while read -r line; do
#    echo "$line"
#    [ "$line" = "updates=0" ] && sleep 2 && pkill -TERM -f "snap/jre/bin/java"
#done


# org.jlinda.jlinda.core \
# org.jlinda.jlinda.nest \
# org.jlinda.jlinda.nest.ui \